### ISSUE TITLE
[bug] malformed GET error on parsing organization issues

### ISSUE THREAD

**Issue by ZeWaka** [jimschubert/labeler-action#1]
**Describe the bug**
Upon making an issue or a PR to an organization repo with this enabled, the action experiences a HTTP 404 error caused by the GET.
I believe this is because the GET is malformed, inserting the author name where it should not.
I tried forking this repo and commenting out the following to no avail: https://github.com/jimschubert/labeler-action/blob/97c0ef699adfb67795517d83303bc6a75764fc11/main.go#L79 
The specific error message is this:
`"Failed to execute GET https://api.github.com/repos/ISSUE_OPENER/ORG_NAME/REPO_NAME/contents/.github?ref=master: 404 Not Found []"`
For an example, please see [here](https://github.com/goonstation/goonstation/runs/583425469?check_suite_focus=true).

**To Reproduce**
1. Open an issue on an organization with this enabled.
2. Notice you have a failing action.

**Expected behavior**
For the GET to not insert the author's name.

**Screenshots**
![image](https://user-images.githubusercontent.com/4741640/79154860-21d5bf00-7d85-11ea-8a3c-d14cc962ae95.png)

**Comment by ZeWaka** [comment]
Looks like this might just be due to a similar error as to https://github.com/actions/labeler/issues/12

**Comment by jimschubert** [comment]
Thanks. I wonder if it might be better to check if the file exists locally (if the repo has been checked out) in a previous step, and fall back to retrieving the raw file from master rather than over the API.

**Comment by jimschubert** [comment]
I've opened #2 to fix the parsing error, I've tested on an ORG and just need to test on owned repo (tomorrow). It doesn't apply labels when coming from a fork but does fix the error.

**Comment by jimschubert** [comment]
I've merged the change which should fix the GET error and result in a green build for PRs from forks. I will need to look at the other issue of not applying labels to PRs from forks. Labels are still applied to issues correctly in my testing.
