### ISSUE TITLE
[Question] No file named labeler.yml found in .github, but file is there

### ISSUE THREAD

**Issue by CristinaHG** [jimschubert/labeler-action#3]
**What is your question?**
Hi, I really would like to use your awesome github action, but I just get a error:
`level=fatal msg="Failed to execute No file named labeler.yml found in .github"` when the action tries to run, and I don't get why, as the file is there, with the name _"labeler.yml"_.

**Where did you look before asking here?**
https://github.com/jimschubert/labeler
https://github.com/marketplace/actions/auto-labeler
**Additional context**
Fist I added my own code, but in a second try I just tried to run the **exact** code from your Readme and the marketplace section. In both cases got the _labeler.yml_ not found in _.github/_ folder. 

Thank you!

**Comment by jimschubert** [comment]
Hey did you close because you figured this out? The file has to exist in master (not a branch or PR)

**Comment by CristinaHG** [comment]
Yes! it is solved now, thanks for the cool tool 👍
